### ISSUE TITLE
Add character type

### ISSUE THREAD

**Issue by yurtsiv** [yurtsiv/mooncake#4]
**Syntax**

```
let a = 'a'
let b = 'b'
let ab = 'ab' # wrong
```

**Semantics**

The behavior of `==`, `>`, `>=`, `<`, `<=` operators should be the same as in Haskell.

f.e.

```
'a' == 'a'  # True
'b' > 'a'    # True
'B' > 'a'    # False
```

**Comment by aitorres** [comment]
Hello! I'm going to submit a PR that adds support for char type, as well as the comparison operators, and both parser and interpreter tests

**Comment by yurtsiv** [comment]
Hello @aitorres, thanks a lot! I'll take a look shortly.
